### ISSUE TITLE
Not operational

### ISSUE THREAD

**Issue by Ricky-Tigg** [LukaJankovic/Ambience#3]
**OS:** Fedora 34; **Environment:** Wayland; **Flatpak component:** 
```
$ flatpak info io.github.lukajankovic.ambience
Ref: app/io.github.lukajankovic.ambience/x86_64/stable
Version: 1.1.1
Runtime: org.gnome.Platform/x86_64/3.38
$ pip list | grep lifxlan
lifxlan            1.2.6
```
```
$ flatpak run -v io.github.lukajankovic.ambience
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/yk/.local/share/flatpak
F: Opening user flatpak installation at path /home/yk/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/yk/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Cleaning up unused container id 3092346681
F: Allocated instance id 1465006699
F: Add defaults in dir /io/github/lukajankovic/ambience/
F: Add locks in dir /io/github/lukajankovic/ambience/
F: Allowing wayland access
F: Running 'bwrap --args 39 xdg-dbus-proxy --args=41'
F: Running 'bwrap --args 39 ambience'
Config file empty
Config file empty
```
Each click on <kbd>**+**</kbd> produces '`Config file empty`'. The interface remains empty be _lifxlan_ installed or not.

![io github lukajankovic ambience_1 1 1](https://user-images.githubusercontent.com/26058215/113305059-52eb2e80-930b-11eb-9194-97f85da1a0d2.png)

**Comment by LukaJankovic** [comment]
The app only initializes a file once it has a light has been added from the discovery list, so that's fine. The issue seems to be that no light is discovered. Apart from the easy stuff (checking that the light is powered on, that you're connected to the same network, etc.) could you try checking if the light is detected by lifxlan?

    $ python3
    >>> from lifxlan import *
    >>> print(LifxLAN().get_lights())

**Comment by Ricky-Tigg** [comment]
```
$ python3
Python 3.9.2 (default, Feb 20 2021, 00:00:00) 
>>> from lifxlan import *
>>> print(LifxLAN().get_lights())
[]
```

**Comment by LukaJankovic** [comment]
So it's confirmed your light isn't being discovered by the api. Did you try adding it manually to the config file like according to the readme?

**Comment by Ricky-Tigg** [comment]
On Flathub pages, there is **no match** in search query against keyword "_ambiance_". Still there,  the dedicated [page](https://flathub.org/apps/details/io.github.lukajankovic.ambience) makes no mention of its **name**! What a pity.

"_light discovery_"; I am having trouble to interpret that sentence. File expected –  ~/.config/lights.json – is missing.  Suggested model relies on version 4 of IP; Is IPv6 supported in that model?

**Comment by LukaJankovic** [comment]
> On Flathub pages, there is no match in search query against keyword "ambiance". Still there, the dedicated page makes no mention of its name! What a pity.

I'm not sure what you mean by this? The app's name is Ambi _e_ nce not Ambi _a_ nce.

The config file is only created once theres something to save, so you can create it manually (or I guess I could add it in the code). As for IPv6, I honestly have no experience with it, so I can't speak on whether it's supported or not. (Nor am I really in a situation where I can try it out practically...)

**Comment by Ricky-Tigg** [comment]
That's was the valid name! As you noticed it yourself, the lack of mention of application name is **common to all applications** on their dedicated pages. Then that must be a deliberate decision of the Flatpak developer team.

When publishing a command – here `cat ~/.config/lights.json` – along with its output,  such as they are in command prompt, a good practise is to mention the Shell prompt mark – e.g.  either "`$`" or "`#`"  for _Bash_ – along with the command as well. That's indeed the only way to mark a command as such and then avoiding confusion. As you currently present it, your command is part of the file's content.

Required file created with permissions 664. No effect.

**Comment by LukaJankovic** [comment]
Thank you for bringing the `$` to my attention. That section wasn't written by me, but I should still have spotted it when I merged the pull request, sorry! 

Does the light appear in the list in Ambience after writing the file?

If not, the issue lies with the [lifxlan](https://github.com/mclarkk/lifxlan) api.

**Comment by Ricky-Tigg** [comment]
Without context depicted in the documentation I could assume the device that can host the file may be a computer. _No effect_; I meant it : then no change appearing in the interface nor in the output  resulting from the execution of `python3`'s sub-commands. Permissions listed by _com.github.tchx84.Flatseal_ applying to this application, seemed to be coherent to me.

**Comment by Arndorferd** [comment]
Getting the same issue

**Comment by mclarkk** [comment]
LIFX bulbs do not support IPv6, they are IPv4 only: https://community.lifx.com/t/any-plans-for-ipv6-support/885/2

@Ricky-Tigg Are your bulbs connected to the network? What are their IP addresses?

**Comment by Arndorferd** [comment]
> $ python3
> >>> from lifxlan import *
> >>> print(LifxLAN().get_lights())

The lights show up here now after troubleshooting with mclarkk, I do this and all the lights show now in lifxlan but still dont show up in ambience.

**Comment by mclarkk** [comment]
FYI there were missing product IDs in the `lifxlan` library. `lifxlan` has been upgraded to version 1.2.7 (including on pip). If anyone (e.g. @Ricky-Tigg) is still having trouble finding devices, try upgrading `lifxlan` with `pip3 install --upgrade lifxlan`. 

After that, based on @Arndorferd's experience, there still may be additional steps required to get things working in Ambience, but at the least the `lifxlan` part works now.

**Comment by mclarkk** [comment]
@Arndorferd Did you try uninstalling Ambience and then reinstalling it fresh?

**Comment by Arndorferd** [comment]
> @Arndorferd Did you try uninstalling Ambience and then reinstalling it fresh?

Yeh it still doesnt work
when I do
> flatpak run io.github.lukajankovic.ambience
it spits out
>Gtk-Message: 03:55:18.230: Failed to load module "appmenu-gtk-module"
>Gtk-Message: 03:55:18.479: Failed to load module "canberra-gtk-module"

**Comment by Arndorferd** [comment]
Im guessing thats just gui stuff though due to it being gtk

**Comment by Ricky-Tigg** [comment]
```
$ pip3 show lifxlan | grep -iE '^version|^summary'
Version: 1.2.7
Summary: API for local communication with LIFX devices over a LAN.
```
@mclarkk; _Are your bulbs connected to the network?_ | Neither mention _bulb_ nor context for this application use can be found within this project documentation. Not yet in position to reply.

**Comment by mclarkk** [comment]
By "bulb" I meant "light" (as in "light bulb"). The LIFX device or devices you want to control.

**Comment by LukaJankovic** [comment]
Sorry for being absent for a while.

@Arndorferd and @Ricky-Tigg are you running Ambience using flatpak? If so, it's still using an older version of lifxlan. I'm going to update to the latest version of lifxlan as well as the latest runtime environment very soon but would it be possible to try compiling / running the app outside of flatpak?

For Fedora the package `libhandy1-devel` as well as the group package "Development Tools" (`# dnf groupinstall "Development Tools"`) and of course `lifxlan` from pip. Then from within the cloned repo:
```
$ meson build --prefix /usr
$ cd build
$ sudo ninja install
```

**Comment by LukaJankovic** [comment]
I just pushed a commit containing updated versions of lifxlan and gnome runtime when running using flatpak. So now the new version should be included when running from i.e. Gnome Builder. Please let me know if it works!

**Comment by Ricky-Tigg** [comment]
@mclarkk | Early after reporting, by "_Without context depicted in the documentation_" i suggested that all the required knowledge to report may not be available. At last thanks to your interventions in the present discussion, it became a certitude. As a result i can now claim without any doubt that this issue observed must have been reported against a wrong condition, which can only explain why it cannot be operational on my system. Till today at least one author – @Arndorferd – encounters an issue that matches this report's title – _Not operational_. Therefore i won't close as  it is usually expected  when there is a third party affected by an issue alive.

@LukaJankovic | runtime not updated to last version.
```
# flatpak --system -y update
$ flatpak info io.github.lukajankovic.ambience | sed -n '5p;8p;14p'
         Ref: app/io.github.lukajankovic.ambience/x86_64/stable
     Version: 1.2.0
     Runtime: org.gnome.Platform/x86_64/3.38
$ pip3 show lifxlan | grep -i ^version
Version: 1.2.7
```

**Comment by Arndorferd** [comment]
Built from source it does function, I dont think its working from flatpak.

**Comment by LukaJankovic** [comment]
Did you build flatpak from the latest commit? It would be strange if it works without flatpak but not with.

Regarding the runtime, here's what I get with the new build:
```
$ flatpak info io.github.lukajankovic.ambience | grep Runtime
     Runtime: org.gnome.Platform/x86_64/40
```

Please try [this](https://github.com/LukaJankovic/Ambience/files/6426815/io.github.lukajankovic.ambience.zip) flatpak image and let me know if it works

**Comment by Arndorferd** [comment]
I type

>flatpak install 'directory of flatpak'

and get

error: The application io.github.lukajankovic.ambience/x86_64/master requires the runtime org.gnome.Platform/x86_64/40 which was not found

but also got

> Skipping: org.gnome.Platform/x86_64/40 is already installed

While trying to install

**Comment by LukaJankovic** [comment]
That is really strange!
I was unable to recreate the problem, but some people [here](https://github.com/flatpak/flatpak/issues/2116) seemed to have a similar issue.

Do you have flathub installed and does `flatpak install org.gnome.Platform//40` work?

**Comment by Arndorferd** [comment]
It works now

**Comment by Arndorferd** [comment]
The flathub version right now is 1.20, the last stable release which appears to be broken. I saw my app get reverted somehow maybe through an update, honestly I would release a new stable version because the current stable is not functional.

**Comment by LukaJankovic** [comment]
I have published the update now, let me know if there's still any issues
